### ISSUE TITLE
Idea: Add Option to include Abiturprüfungen

### ISSUE THREAD

**Issue by konradpa** [wwhtrbbtt/notenrechner#1]
since they count double I think

**Comment by pagpeter** [comment]
Hey,
You can already give some classes more weight than others by making the multiplier higher.
<img width="1169" alt="Bildschirmfoto 2023-12-22 um 12 13 38" src="https://github.com/wwhtrbbtt/notenrechner/assets/64318024/ee511e6e-45fb-433f-a76e-d2031e2a3f46">
This is a simplified example, but if you figure out all the weights, you should be able to calculate your average
Bis Morgen :)
